language: php

matrix:
  include:
    - php: '5.6'
    - php: '7.0'
    - php: '7.1'
    - php: hhvm
  fast_finish: true

before_script:
  - chmod 777 ./tests/travis/setup_arangodb.sh
  - ./tests/travis/setup_arangodb.sh

script: 
  - ./phpunit --configuration ./tests/phpunit-connection-close.xml
  - ./phpunit --configuration ./tests/phpunit-connection-keep-alive.xml

after_script:
  - ./tests/travis/teardown_arangodb.sh
